version: '3.9'
services:
  app:
    ports:
      - 3000:3000
    build: 
      context: frontend
    tty: true
    volumes:
      - ./frontend:/app # フォルダを同期
    environment:
      - WATCHPACK_POLLING=true # ホットリロード
    entrypoint: "yarn dev"